"""redesign for dynamic interviews

Revision ID: b518456ea551
Revises: bc16035f38b3
Create Date: 2026-06-04 01:42:25.145776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b518456ea551'
down_revision: Union[str, None] = 'bc16035f38b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Wipe all data dependent on interviews to allow adding NOT NULL columns without defaults.
    # In dev this clears test data; in CI/fresh DBs it's a no-op.
    op.execute("TRUNCATE TABLE interviews CASCADE")

    # candidate_sessions: new nullable columns
    op.add_column('candidate_sessions', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('candidate_sessions', sa.Column('candidate_profile', sa.Text(), nullable=True))

    # interviews: remove Phase 1 columns, add Phase 2 columns
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interviews', 'title')
    op.drop_column('interviews', 'topics')
    op.add_column('interviews', sa.Column('job_title', sa.String(length=200), nullable=False))
    op.add_column('interviews', sa.Column('job_description', sa.Text(), nullable=False))
    op.add_column('interviews', sa.Column('required_skills', sa.Text(), nullable=False))
    op.add_column('interviews', sa.Column('role_level', sa.String(length=20), nullable=False))
    op.add_column('interviews', sa.Column('max_questions', sa.Integer(), nullable=False,
                                          server_default='10'))

    # responses: add question_text and is_follow_up (table is empty after CASCADE above)
    op.add_column('responses', sa.Column('question_text', sa.Text(), nullable=False,
                                          server_default=''))
    op.add_column('responses', sa.Column('is_follow_up', sa.Boolean(), nullable=False,
                                          server_default=sa.text('false')))
    op.alter_column('responses', 'question_id', existing_type=sa.UUID(), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('responses', 'is_follow_up')
    op.drop_column('responses', 'question_text')
    op.add_column('interviews', sa.Column('topics', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('interviews', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('interviews', sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('interviews', 'max_questions')
    op.drop_column('interviews', 'role_level')
    op.drop_column('interviews', 'required_skills')
    op.drop_column('interviews', 'job_description')
    op.drop_column('interviews', 'job_title')
    op.drop_column('candidate_sessions', 'candidate_profile')
    op.drop_column('candidate_sessions', 'resume_text')
    # ### end Alembic commands ###
